### ISSUE TITLE
[9.0]product Wishlist make XMLRPC authenticationb fail

### ISSUE THREAD

**Issue by flotho** [OCA/e-commerce#189]
Hi,
I'm trying to login through xmlRPC and I have this kind of issue :
```
2017-06-26 15:38:22,795 4749 ERROR revivre openerp.http: object unbound
Traceback (most recent call last):
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/service/common.py", line 23, in exp_login
    res = security.login(db, login, password)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/service/security.py", line 9, in login
    return res_users._login(db, login, password)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/addons/base/res/res_users.py", line 462, in _login
    self.check_credentials(cr, user_id, password)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/Libs/OCA-ecommerce/website_sale_wishlist/models/res_users.py", line 27, in check_credentials
    self.env["product.wishlist"]._join_current_user_and_session()
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/EclipseWorkSpace/Odoo/Revivre/Libs/OCA-ecommerce/website_sale_wishlist/models/product_wishlist.py", line 72, in _join_current_user_and_session
    ("session", "=", request.session.id),
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 135, in _lookup
    raise RuntimeError('object unbound')
RuntimeError: object unbound
```
Anyone could help me on this ?
The usual connexion through the UI works perfectly.

regards

**Comment by flotho** [comment]
Almost Duplicate with #152
