### ISSUE TITLE
Odoo server error when inspecting module website_sale_product_brand

### ISSUE THREAD

**Issue by pjmcdermott** [OCA/e-commerce#57]
The module `website_sale_product_brand` causes an Odoo server error when one clicks on it to see the modules description in Local Modules list or icon view.

Here is the error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3143, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3178, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3357, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/site-packages/openerp/osv/fields.py", line 1453, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 187, in _get_desc
    output = publish_string(source=module.description or '', settings_overrides=overrides, writer=MyWriter())
  File "/usr/lib/python2.7/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2961, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2738, in text
    source=src, line=srcline)
  File "/usr/lib/python2.7/site-packages/docutils/utils/__init__.py", line 227, in error
    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docutils/utils/__init__.py", line 191, in system_message
    self.stream.write(msg.astext() + '\n')
  File "/usr/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 189, in write
    self.stream.write(data)
IOError: [Errno 32] Broken pipe
```

**Comment by pedrobaeza** [comment]
I suppose you are talking about website_sale_product_brand, but I have tried on runbot and there's no error, so I close the issue. Please check your installation.

**Comment by pjmcdermott** [comment]
I think it is choking on an indentation error in `README.rst`. From the server logs after I click on the icon:

```
Oct 01 01:18:52 larkfield openerp-server[13907]: <string>:40: (ERROR/3) Unexpected indentation.
Oct 01 01:18:52 larkfield openerp-server[13907]: <string>:41: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
Oct 01 01:18:52 larkfield openerp-server[13907]: Odoo Server 8.0-20150916:larkfield:WARNING:openerp.addons.base.module.module:docutils' system message present: <system_message level="3" line="40" source="<string>" type="ERROR"><paragraph>Unexpected indentation.</paragraph></system_message>
Oct 01 01:18:52 larkfield openerp-server[13907]: Odoo Server 8.0-20150916:larkfield:WARNING:openerp.addons.base.module.module:docutils' system message present: <system_message level="2" line="41" source="<string>" type="WARNING"><paragraph>Block quote ends without a blank line; unexpected unindent.</paragraph></system_message>
```

A quick check with check with rstcheck:

```
$ rstcheck README.rst 
README.rst:40: (ERROR/3) Unexpected indentation.
```

Strangely I am now getting the module description come up, but I still get the error message in the log

**Comment by pedrobaeza** [comment]
OK, I understand you now. It's not a blocking issue anyway, but it's fixed in https://github.com/OCA/e-commerce/commit/6e374bf0c47dba8ff213d27bd023220286f3dad6
