### ISSUE TITLE
Module 'Website Sale Product Minimal Price' bug/error

### ISSUE THREAD

**Issue by ratimir-matana** [OCA/e-commerce#602]
module: website_sale_product_minimal_price
version: 14.0

**Steps to reproduce**
![Selection_343](https://user-images.githubusercontent.com/44779588/148209466-671bb790-67d6-4c77-a5c3-02bb75e381cc.png)

- Module installation
- Website > Go to Website > Shop

**Current behavior**
On opening Shop (Website > Go to Website > Shop) Odoo Client Error popups:

Traceback:
Traceback:
Error: QWeb2: Template 'website_sale_product_minimal_price.from_view' not found
    at Object.exception (https://url/web/content/779-3e6639e/1/web.assets_common_lazy.js:4320:7)
    at Engine._render (https://url/web/content/779-3e6639e/1/web.assets_common_lazy.js:4365:103)
    at Engine.render (https://url/web/content/779-3e6639e/1/web.assets_common_lazy.js:4361:151)
    at https://url/web/content/941-9d47cd4/1/web.assets_frontend_lazy.js:515:71
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 52)
    at async Promise.all (index 1)

**Expected behavior**

The text “From ” with minimal price appears if the product has a distinct prices by attribute

**Comment by CarlosRoca13** [comment]
Can you reproduce this in runboat? https://runboat.odoo-community.org/webui/builds.html?repo=OCA/e-commerce&target_branch=14.0
