### ISSUE TITLE
 website_sale_stock_available error message for missing field

### ISSUE THREAD

**Issue by nugica** [OCA/e-commerce#668]
## Module
website_sale_stock_available

## Describe the bug
On opening a product from the product list we get an error message (see below).

## To Reproduce
We have only installed the module.
System is Odoo 14 Enterprise

**ERROR MESSAGE**
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1394, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 3011, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'immediately_usable_qty' on model 'product.template'

**Comment by chienandalu** [comment]
Looks more like you didn't install the module correctly.

**Comment by nugica** [comment]
Thank you - yes, we do believe so, but we haven't found resources on how to correctly install.

**Comment by pedrobaeza** [comment]
Sorry, this issue tracker can only be used for issues with the modules, not with deployments. Please go to forums.

**Comment by nugica** [comment]
Where can I get help? I don't find a contact person! What forums are there?
I registered at the odoo forums - but as already known nothing works in odoo, not even their own websites - I only get error messages like 403 and 500 server errors.
What forums can I find help?

**Comment by pedrobaeza** [comment]
I'm talking about Odoo forums, but take into account that this is free software and there are no guarantees of anything.
