### ISSUE TITLE
[14.0] website_sale_cart_expire

### ISSUE THREAD

**Issue by matteoopenf** [OCA/e-commerce#755]
## Module
website_sale_cart_expire

## Describe the bug
when the cron run i obtain that errore:
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 331, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/b_OCA/e-commerce/website_sale_cart_expire/models/website.py", line 45, in _scheduler_website_expire_cart
    carts_to_expire.action_cancel()
  File "/home/odoo/src/odoo/addons/sale/models/sale.py", line 825, in action_cancel
    'context': {'default_order_id': self.id},
  File "/home/odoo/src/odoo/odoo/fields.py", line 3822, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: sale.order(34961, 34933, 34927, 34923, 34914, 34893, 34867, 34856, 34830, 34807, 34806, 34782, 34123, 34757, 34753, 34752, 34727, 34714, 34708, 34691, 34690, 34689, 34631, 34613, 34579, 34578, 34576, 34562, 34530, 34507, 34464, 34451, 34438, 34415, 34402, 34395, 34372, 3

## To Reproduce
**Affected versions**:

- [x] 14.0 https://github.com/OCA/e-commerce/pull/756

1. install module
2. not finish some order on website
3. obtain error

**Expected behavior**
there is no  error

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Please don't open an issue if you are going to put a PR. Just put the issue text in the PR (and in the commit message).
