### ISSUE TITLE
Get an error when installing the module

### ISSUE THREAD

**Issue by drzaphod85** [OCA/e-commerce#817]
module: website_sale_hide_price
version: 16.0

**Steps to reproduce**
Try to install module on Odoo 25th June version

**Current behavior**
Get this error message:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:47
Error when validating view:

Elementet "<xpath expr="//a[hasclass(&#39;o_we_buy_now&#39;)]">" Cannot be found in the parent view.

View error context:
{'file': '/opt/addons/website_sale_hide_price/views/website_sale_template.xml',
 'line': 2,
 'name': 'product_buy_now',
 'view': ir.ui.view(4771,),
 'view.model': False,
 'view.parent': ir.ui.view(3216,),
 'xmlid': 'product_buy_now'}

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://192.168.50.39:8069/web/assets/3262-440d65c/web.assets_backend.min.js:988:279
    makeErrorFromResponse@http://192.168.50.39:8069/web/assets/3262-440d65c/web.assets_backend.min.js:992:175
    @http://192.168.50.39:8069/web/assets/3262-440d65c/web.assets_backend.min.js:1000:34

**Expected behavior**

Module loaded and worked as described .

**Comment by chienandalu** [comment]
Looks like you may have some modified views at website level. Search for the view with the key  website_sale_hide_price.product_buy_now  that is linked to your website and look for the differences with main one

**Comment by drzaphod85** [comment]
If I remove the template from the file it installed just find. I have tried to install the file on a clean installation of Odoo 16 and get the same error that this does not work.

   ```
 <!-- Hide buy now button if "Buy Now Button" option is enabled and not website_show_price -->
<!--
    <template id="product_buy_now" inherit_id="website_sale.product_buy_now">
        <xpath expr="//a[hasclass('o_we_buy_now')]" position="attributes">
            <attribute name="t-if">
                website.website_show_price and not product.website_hide_price
            </attribute>
        </xpath>
    </template>
-->
    <!-- Hide add to cart button if "Add to cart" option is enabled and not website_show_price -->

```
