### ISSUE TITLE
website_sale_hide_price 16.0.1.3.0 can't be upgraded over 16.0.1.2.1

### ISSUE THREAD

**Issue by kubangab** [OCA/e-commerce#847]
## Module
website_sale_hide_price

## Describe the bug
When updating the module I get the following error from Odoo 16 on-prem installation.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-80>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 647, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 580, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:68
Error while validating view:

Element '<xpath expr="//a[hasclass(&#39;o_we_buy_now&#39;)]">' cannot be located in parent view

View error context:
{'file': '/opt/addons/website_sale_hide_price/views/website_sale_template.xml',
 'line': 2,
 'name': 'product_buy_now',
 'view': ir.ui.view(5017,),
 'view.model': False,
 'view.parent': ir.ui.view(3216,),
 'xmlid': 'product_buy_now'}

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://192.168.50.60:8069/web/assets/4021-79d0bfc/web.assets_backend.min.js:988:279
    makeErrorFromResponse@http://192.168.50.60:8069/web/assets/4021-79d0bfc/web.assets_backend.min.js:992:175
    @http://192.168.50.60:8069/web/assets/4021-79d0bfc/web.assets_backend.min.js:1000:34

## To Reproduce

1. Install version 16.0.1.3.0 on a machine with version 16.0.1.2.1
2. Restart Server with service odor restart
3. In the App module select the website_sale_hide_price module and select Upgrade

**Expected behavior**
The module would be installed on the server and run like it should.

**Additional context**
Server running on Ubuntu 22.04.3, python version 3.10.12.

**Comment by pedrobaeza** [comment]
The module is working on runboat, so something in your DB seems incorrect or messy. Please try on a fresh DB. If you still find problems, please comment back. Meanwhile, we close it.

**Comment by drzaphod85** [comment]
Hi Pedro,

Not sure how to fresh the DB to try and fix the problem. Is this some tool I need to use for this?

regards,

Lasse...
