### ISSUE TITLE
Variant error when module is installed.

### ISSUE THREAD

**Issue by willievmobile** [OCA/e-commerce#853]
When the hide price module is installed, when creating a quote from the sales module when a product is selected that has variants instead of opening the popup to choose the variant there's a error: - even after uninstalling the module i still get the same error and had to revert odoo back to a previous backup to get it to go away....

`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "<1352>", line 94, in template_1352
  File "<1352>", line 9, in template_1352_content
KeyError: 'website'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/cloudclusters/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/cloudclusters/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/cloudclusters/odoo/odoo/http.py", line 1808, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/cloudclusters/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/cloudclusters/odoo/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/cloudclusters/odoo/addons/sale_product_configurator/controllers/main.py", line 30, in configure
    return request.env['ir.ui.view']._render_template(
  File "/cloudclusters/odoo/addons/website/models/ir_ui_view.py", line 418, in _render_template
    return super()._render_template(template, values=values)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_ui_view.py", line 2128, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/cloudclusters/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<1440>", line 227, in template_1440
  File "<1440>", line 88, in template_1440_content
  File "<1351>", line 564, in template_1351
  File "<1351>", line 336, in template_1351_content
  File "<1352>", line 100, in template_1352
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'website'
Template: sale.badge_extra_price
Path: /t
Node: <t name="Badge Extra Price" t-if="website.website_show_price and not product.website_hide_price"/>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://www.yougoltd.com/web/assets/3514-63e5132/web.assets_backend.min.js:965:274
    makeErrorFromResponse@https://www.yougoltd.com/web/assets/3514-63e5132/web.assets_backend.min.js:969:163
    jsonrpc/promise</<@https://www.yougoltd.com/web/assets/3514-63e5132/web.assets_backend.min.js:977:34`

==============================

As a second error now i cant try and install the module again as i get a error :

'The operation cannot be completed: duplicate key value violates unique constraint "res_partner_pkey"
DETAIL:  Key (id)=(113) already exists.'

i would really like to hide the prices on the website as they are supposed to be for info on the products only, not pricing..

Thank you !

**Comment by chienandalu** [comment]
Hi @willievmobile what version are we talking about? Are you able to reproduce it in a OCA runboat for that version?

**Comment by willievmobile** [comment]
Sorry its on 16 CE. i dont know how the runboats work unfortunately?
