### ISSUE TITLE
[16.0] website_sale_checkout_skip_payment not installing

### ISSUE THREAD

**Issue by woutercloete** [OCA/e-commerce#892]
## Module
website_sale_checkout_skip_payment

## Describe the bug
The module "website_sale_checkout_skip_payment" does not install. The following error is displayed:
============
raceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 468, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 757, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 209, in file_open
    path = file_path(name, filter_ext=filter_ext, env=env)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 188, in file_path
    raise FileNotFoundError("File not found: " + file_path)
FileNotFoundError: File not found: website_sale_checkout_skip_payment/views/assets.xml

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://192.168.1.100:8072/web/assets/3374-1ba304f/web.assets_backend.min.js:989:163)
    at XMLHttpRequest.<anonymous> (http://192.168.1.100:8072/web/assets/3374-1ba304f/web.assets_backend.min.js:997:13)
============

## To Reproduce
Click on the "ACTIVATE" button on the  "Website Sale Checkout Skip Paymnet" module within the "Apps" section of Odoo.

**Affected versions**:
Version 16.0.14.0.1.2.0

**Expected behavior**
The module should install without errors

**Comment by chienandalu** [comment]
This is very likely something about your local setup. There's no such version for the  module, btw: https://github.com/OCA/e-commerce/blob/16.0/website_sale_checkout_skip_payment/__manifest__.py#L8

**Comment by woutercloete** [comment]
My mistake the manifest shows version: "16.0.1.1.0"

**Comment by chienandalu** [comment]
Anyway, you can check in any clean runboat that there's no issue with the module: https://runboat.odoo-community.org/webui/builds.html?repo=OCA/e-commerce&target_branch=16.0
