### ISSUE TITLE
Error during instalation on server [Odoo15]

### ISSUE THREAD

**Issue by DWitchKing** [OCA/e-commerce#930]
module: website_sale_checkout_skip_payment
version: 15.0

**Steps to reproduce**
- I have created new database
- Pressed install button on your module

**Current behavior**
Traceback (most recent call last):
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 658, in _tag_template
    return self._tag_record(record)
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/local/www/odoo15/odoo/models.py", line 4406, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/local/www/odoo15/odoo/models.py", line 4335, in _load_records_create
    return self.create(values)
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/www/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/usr/local/www/odoo15/addons/website/models/ir_ui_view.py", line 57, in create
    return super().create(vals_list)
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/www/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 539, in create
    result = super(View, self.with_context(ir_ui_view_partial_validation=True)).create(vals_list)
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/www/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/www/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/usr/local/www/odoo15/odoo/models.py", line 4071, in create
    records = self._create(data_list)
  File "/usr/local/www/odoo15/odoo/models.py", line 4236, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/usr/local/www/odoo15/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 430, in _check_xml
    raise err from None
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 421, in _check_xml
    combined_arch = view._get_combined_arch()
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 984, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 925, in _combine
    combined_arch = view.apply_inheritance_specs(combined_arch, arch)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 862, in apply_inheritance_specs
    self._raise_view_error(str(e), specs_tree)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_ui_view.py", line 739, in _raise_view_error
    raise err from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Element '<xpath expr="//t[@name=&#39;website_sale_non_free_cart&#39;]">' cannot be located in parent view

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/local/www/odoo15/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/www/odoo15/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/www/odoo15/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/www/odoo15/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/www/odoo15/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/usr/local/www/odoo15/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/www/odoo15/addons/web/controllers/main.py", line 1339, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/local/www/odoo15/addons/web/controllers/main.py", line 1327, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/www/odoo15/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/local/www/odoo15/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/local/www/odoo15/odoo/addons/base/models/ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/www/odoo15/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/local/www/odoo15/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/local/www/odoo15/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/local/www/odoo15/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/local/www/odoo15/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/usr/local/www/odoo15/odoo/tools/convert.py", line 691, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/www/odoo15/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/www/odoo15/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing None:5
Error while validating view:

Element '<xpath expr="//t[@name=&#39;website_sale_non_free_cart&#39;]">' cannot be located in parent view

View error context:
{'file': '/usr/home/odoouser/odoo_acs/website_sale_checkout_skip_payment/views/website_sale_template.xml',
 'line': 2,
 'name': 'payment',
 'view': ir.ui.view(1980,),
 'view.model': False,
 'view.parent': ir.ui.view(1840,),
 'xmlid': 'payment'}
**Expected behavior**
Successful instalation

**Comment by chienandalu** [comment]
This is normally due to custom website views which don't have the expected hooks for the module to work.

**Comment by DWitchKing** [comment]
I didnt do any customisation. At first I thought it was because of running
database(with adding and customisation) but when I created new database
problem prevailed.
